spring.application.name=moattravel

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/moattravel3_db?allLocalSessionVariables=true

spring.datasource.username=root

spring.datasource.password=Sashiwa0713!

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.sql.init.encoding=utf-8

spring.jpa.hibernate.ddl-auto=update

spring.sql.init.mode=always

spring.mail.host=smtp.gmail.com

spring.mail.port=2525
spring.mail.username=sashiwa0713naoto@gmail.com

spring.mail.password=kozmohaoszzabtnr

spring.mail.properties.mail.smtp.auth=true

spring.mail.properties.mail.smtp.starttls.enable=true

# 実行されたSQLログを出力する設定
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ? にバインドされた実際の値（パラメータ）をログに出力する設定
logging.level.org.hibernate.orm.jdbc.bind=TRACE


stripe.webhook-secret=whsec_a1da68571ac93946d4c91ecc6ea14ded7763b95dbd6e82d1a12df28e0c440120


stripe.api-key=sk_test_51TiXru8vIMH9ANyD8yWfRkh6wOT4TPEiuR61bYLQFwgOOaJHXe4HYvPpHnvdwDEhij3zIytxFjfvBoqmi0VRI3c900ujUQ3fgC

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect